# Generated by Django 5.1.4 on 2025-08-18 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuku_ai_bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tgfile',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
