# Generated by Django 5.1.4 on 2025-08-27 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuku_ai_bot', '0002_alter_tgfile_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Kategoriya nomi')),
                ('slug', models.SlugField(help_text='URL uchun avtomatik generatsiya qilinadi', max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='subscribechannel',
            name='bot',
            field=models.ForeignKey(help_text='The bot that manages this channel.', on_delete=django.db.models.deletion.CASCADE, related_name='subscription_channels', to='kuku_ai_bot.bot'),
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Subkategoriya nomi')),
                ('slug', models.SlugField(help_text='URL uchun avtomatik generatsiya qilinadi', max_length=100, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='kuku_ai_bot.category', verbose_name='Asosiy Kategoriya')),
            ],
            options={
                'verbose_name': 'Subkategoriya',
                'verbose_name_plural': 'Subkategoriyalar',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.AddField(
            model_name='tgfile',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kuku_ai_bot.subcategory', verbose_name='Subkategoriya'),
        ),
        migrations.CreateModel(
            name='InvitedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField()),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('username', models.CharField(blank=True, max_length=100, null=True)),
                ('invited_at', models.DateTimeField(auto_now_add=True, verbose_name='Invited At')),
                ('left', models.BooleanField(default=False, verbose_name='Left the Channel')),
                ('left_at', models.DateTimeField(blank=True, null=True, verbose_name='Left At')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invited_members', to='kuku_ai_bot.subscribechannel', verbose_name='Channel')),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invited_users', to='kuku_ai_bot.user', verbose_name='Invited By')),
            ],
            options={
                'verbose_name': 'Invited User',
                'verbose_name_plural': 'Invited Users',
                'ordering': ['-invited_at'],
                'unique_together': {('channel', 'telegram_id')},
            },
        ),
    ]
